# See http://about.travis-ci.org/docs/user/build-configuration/
sudo: required
dist: trusty

before_install:
  - unset _JAVA_OPTIONS

before_script:
  - export MAVEN_SKIP_RC=true

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

script:
  - export MAVEN_OPTS="-Xmx1g -Djava.net.preferIPv4Stack=true"
  - ./.travisbuild.sh
