name: build-and-test_2.13

on:
  push:
  pull_request:

jobs:
  build-scala:
    runs-on: ubuntu-latest
    # avoid duplicate jobs on PRs from the main repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Set Scala version
        run: ./build/change-scala-version.sh 2.13
      - name: Build with Maven
        run: mvn clean install -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
      - name: Remove GeoMesa artifacts
        run: |
          rm -rf ~/.m2/repository/org/geomesa/nifi
